### ISSUE TITLE
Gas simulation on send with both receive and swap assets the same triggers a recursive swap error 

### ISSUE THREAD

**Issue by cmancrypto** [Orchestra-Labs/Browser-Extension-Wallet#48]

**Comment by dblackstone1** [comment]
that should be fixed on the latest.  fee and exchange checks for swaps should only occur if the transaction is a swap, otherwise it should check on send

**Comment by dblackstone1** [comment]
yeah, don't know how to reproduce this so i think it's fixed

**Comment by cmancrypto** [comment]
Perfect
